<?php
/** @var \Akulov\ThreeFormsOfVerbs\Block\Forms $block */
?>
<?php $items = $block->getItems(); ?>
<?php $itemsRand = $block->getRandomItems(); ?>

<table>
    <tbody>
    <?php foreach ($itemsRand as $itemRand): ?>
        <?php foreach ($items as $item): ?>
            <?php if ($item->getId() == $itemRand): ?>
                <tr>
                    <td>
                        <?php echo $item->getId(); ?>
                    </td>
                    <td>
                        <?php echo $item['translate']; ?>
                    </td>
                    <td>
                        <?php echo $item['first']; ?>
                    </td>
                    <td>
                        <?php echo $item['second']; ?>
                    </td>
                    <td>
                        <?php echo $item['third']; ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>
